### PR TITLE
Adds null-safety support

### PR DESCRIPTION
**Pull request by ccosnean**

### CODE REVIEW

**Comment by pak3nuh** [comment]
Hi @ccosnean 
I'm sorry you had all this trouble, but not having null safety was a design choice.
I have consumers of this project that aren't null safe yet and I can't evolve right now.

**Comment by ccosnean** [comment]
> Hi @ccosnean
> I'm sorry you had all this trouble, but not having null safety was a design choice.
> I have consumers of this project that aren't null safe yet and I can't evolve right now.

@pak3nuh No troubles, i need the null-safety now, and updated it, gonna use it from my fork.
```yaml
  dart_pact_consumer:
    git:
      url: git://github.com/ccosnean/dart_pact_consumer.git
```

i'm gonna be looking forward for the migration.

**Comment by twwd** [comment]
Dart allows to use null safe packages from non-null safe projects (_unsound null safety_) to it should be no issue to make this package null safe. See https://dart.dev/null-safety/migration-guide

The other way round is not possible, thus it would be great if this package could get null safety.

**Comment by pak3nuh** [comment]
@twwd AFAIK having null safety requires a bump in the minimum SDK to 2.12, which directly impacts users of this package.
A bump to >= 2.12 is planed, not just for null safety, but first I'd like to reach a stable feature set.

**Comment by neokree** [comment]
@pak3nuh When this PR will be merged? Nowadays every flutter project support null-safety

**Comment by GoncaloPT** [comment]
@pak3nuh not sure if I know the consumers of this package you're referring in your comment. Currently"our" project is fully migrated to flutter 2.

**Comment by pak3nuh** [comment]
@neokree can't give you a timeline, but I'd like to spend some time upgrading this. Not only I'd like to increase the SDK to null safety, but to a stable FFI build and be able to upgrade the native binaries this lib uses.

Still not sure if the upgrade will go through merging this PR with additional tweaks or a different one.

**Comment by neokree** [comment]
Ok sure I understand, please take your time to check it

Meanwhile in my company we are testing Pact to see if it fit with us. 
We have a mobile app that uses Flutter 2, probably we will migrate to Flutter 3 later this year. 
If it will be chosen for integration testing I will also ask if we can help with the support of this library, since it would become an important tool

**Comment by pak3nuh** [comment]
@neokree as long as our goals align we might collaborate, lets see how this evolves. Nevertheless will be super helpful to have feedback on which things work and which need improvements.

I've opened #12 to not clutter this PR with more noise. Anything else, please comment on that issue.

**Comment by pak3nuh** [comment]
Hey all,

Sorry for the late update,  but finally I have a PR that adds null safety to this package.
I'll leave it open for a couple of days to check on feedback if you want to try.

Check out #13

**Pull request closed without merging**
